.TH etherape 1 "EtherApe Manual Page" ""
.SH NAME
etherape \- graphical network traffic browser
.SH SYNOPSIS
.B etherape
[
.B -d 
] [
.B -f
filter ] [
.B --glade-file
gladefile ] [
.B -i
interface ] [
.B -l
maxnodes ] [
.B -m
operating mode ] [
.B --max-delay
delay ] [
.B -n 
] [
.B -q
] [
.B -r
inputfile ] [
.B -s
]

.SH DESCRIPTION
.PP
.B etherape
is a network traffic browser. It displays network activity
graphically. It uses GNOME libraries as its user interface, and
libpcap, a packet capture and filtering library.
.SH OPTIONS
.PP
These options can be supplied to the command:
.TP
.BR "-d, --diagram-only"
don't display any node text identification
.TP
.BR "-f, --filter " "<capture filter>"
set capture filter
.TP
.BR "--glade-file " "<filename>"
uses the named libglade file to load interface instead of the default.
.TP
.BR "-i, --interface " "<interface name>"
set interface to listen to
.TP
.BR "-l, --node-limit " "<number>"
sets the maximum number of node visible
.TP
.BR "-m, --mode " "<link|ip|tcp>"
set mode of operation (default is ip)
.TP
.BR "--max-delay " "<delay in ms>"
caps timestamps to the provided delay when replaying a capture file.
.TP
.BR "-n, --numeric"
don't convert addresses to names, disables name resolution.
.TP
.BR "-q"
disables informational messages.
.TP
.BR "-r, --replay-file " "<file name>"
sets input file to replay
.TP
.BR "-s"
Place nodes using an alternate algorithm. 
.B
Deprecated.
.TP
.BR "-?, --help"
show a brief help message
.SH ENVIRONMENT VARIABLES
.TP
.BR "APE_DEBUG=" "normal|info|debug"
controls debug output verbosity. Debug informations are printed on
standard output.
.SH FILES
Etherape will use
.I /etc/ethers
if there is one to convert MAC addresses to names.

.SH SEE ALSO
.PP
The etherape webpage at http://etherape.sourceforge.net/

.SH AUTHOR

Juan Toledo <toledo@users.sourceforge.net>
Riccardo Ghetta <bchiara@users.sourceforge.net>

