/* Automatically generated by po2tbl.sed from etherape.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"Creating canvas_node: %s. Number of nodes %d", 2},
  {"._New File", 3},
  {"Etherape", 4},
  {"Nuevo", 5},
  {"Nuevo archivo", 6},
  {"Abrir", 7},
  {"Abrir archivo", 8},
  {"Guardar", 9},
  {"Guardar archivo", 10},
  {"Copyright 2000 Juan Toledo", 11},
  {"\
A Graphical Network Browser.\n\
Web: http://etherape.sourceforge.net", 12},
  {"Couldn't find pixmap file: %s", 13},
  {"Couldn't create pixmap from file: %s", 14},
  {"Creating node: %s. Number of nodes %d", 15},
};

int _msg_tbl_length = 15;
