/* Automatically generated by po2tbl.sed from etherape.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"don't convert addresses to names", 2},
  {"don't display any node text identification", 3},
  {"mode of operation", 4},
  {"<ethernet|ip|tcp|udp>", 5},
  {"set interface to listen to", 6},
  {"<interface name>", 7},
  {"set capture filter", 8},
  {"<capture filter>", 9},
  {"makes diagram more readable when it is crowded", 10},
  {"do not fade old links", 11},
  {"set the node color", 12},
  {"color", 13},
  {"set the link color", 14},
  {"set the text color", 15},
  {"Unrecognized mode. Do etherape --help for a list of modes", 16},
  {"._New File", 17},
  {"Etherape", 18},
  {"New", 19},
  {"Nuevo archivo", 20},
  {"Open", 21},
  {"Abrir archivo", 22},
  {"Save", 23},
  {"Guardar archivo", 24},
  {"Diagram settings", 25},
  {"Averaging Time (ms)", 26},
  {"Diagram refresh period (ms)", 27},
  {"Max. Node Radius", 28},
  {"Max. Link Width", 29},
  {"Node Timeout (ms)", 30},
  {"Link Timeout (ms)", 31},
  {"Protocols", 32},
  {"Copyright 2000 Juan Toledo", 33},
  {"\
A Graphical Network Browser.\n\
Web: http://etherape.sourceforge.net", 34},
  {"window1", 35},
  {"name", 36},
  {"accumulated", 37},
  {"average", 38},
  {"This message is not here yet. (Don´t tell anybody you saw it ;-) )", 39},
  {"Adjustment value: %g. Radius multiplier %g", 40},
  {"Couldn't find pixmap file: %s", 41},
  {"Couldn't create pixmap from file: %s", 42},
  {"Reached default in fill_names", 43},
  {"n/a", 44},
  {"Creating node: %s. Number of nodes %d", 45},
  {"Creating link: %s-%s. Number of links %d", 46},
  {"Null packet in check_packet", 47},
  {"Reached default in get_node_id", 48},
  {"Unsopported ape mode in get_link_id", 49},
  {"Error getting device: %s", 50},
  {"Error opening %s : %s - perhaps you need to be root?", 51},
  {"Can't use filter:  Couldn't obtain netmask info (%s).", 52},
  {"Unable to parse filter string (%s).", 53},
  {"Can't install filter (%s).", 54},
  {"Mode not available in this device", 55},
  {"Link type not yet supported", 56},
  {"Ape mode not yet supported", 57},
};

int _msg_tbl_length = 57;
