/* Automatically generated by po2tbl.sed from etherape.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"don't convert addresses to names", 2},
  {"use IP name resolving. Caution! Long timeouts!", 3},
  {"don't display any node text identification", 4},
  {"run in interape mode", 5},
  {"set interface to listen to", 6},
  {"<interface name>", 7},
  {"set capture filter", 8},
  {"<capture filter>", 9},
  {"sets the node color", 10},
  {"color", 11},
  {"sets the link color", 12},
  {"sets the text color", 13},
  {"._New File", 14},
  {"Etherape", 15},
  {"New", 16},
  {"Nuevo archivo", 17},
  {"Open", 18},
  {"Abrir archivo", 19},
  {"Save", 20},
  {"Guardar archivo", 21},
  {"Diagram settings", 22},
  {"Averaging Time (ms)", 23},
  {"Diagram refresh period (ms)", 24},
  {"Max. Node Radius", 25},
  {"Max. Link Width", 26},
  {"Node Timeout (ms)", 27},
  {"Link Timeout (ms)", 28},
  {"Place Holder for The Color Coded Protocols display", 29},
  {"Copyright 2000 Juan Toledo", 30},
  {"\
A Graphical Network Browser.\n\
Web: http://etherape.sourceforge.net", 31},
  {"window1", 32},
  {"Name", 33},
  {"IP Name", 34},
  {"IP Address", 35},
  {"Ether Name", 36},
  {"Ether Address", 37},
  {"Accum. bytes", 38},
  {"Average bps", 39},
  {"average", 40},
  {"accumulated", 41},
  {"ether address", 42},
  {"ether name", 43},
  {"ip address", 44},
  {"ip host name", 45},
  {"name", 46},
  {"This message is not here yet. (Don´t tell anybody you saw it ;-) )", 47},
  {"Adjustment value: %g. Radius multiplier %g", 48},
  {"Couldn't find pixmap file: %s", 49},
  {"Couldn't create pixmap from file: %s", 50},
  {"n/a", 51},
  {"Creating node: %s. Number of nodes %d", 52},
  {"Creating link: %s-%s. Number of links %d", 53},
  {"Error getting device: %s", 54},
  {"Error opening %s : %s - perhaps you need to be root?", 55},
  {"Can't use filter:  Couldn't obtain netmask info (%s).", 56},
  {"Unable to parse filter string (%s).", 57},
  {"Can't install filter (%s).", 58},
};

int _msg_tbl_length = 58;
