/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

GtkWidget *
create_window_main (void)
{
  GtkWidget *window_main;
  GtkWidget *vbox1;
  GtkWidget *menubar1;
  guint tmp_key;
  GtkWidget *file1;
  GtkWidget *hpaned1;
  GtkWidget *drawingarea1;
  GtkWidget *hscale1;
  GtkWidget *statusbar1;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  window_main = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_object_set_data (GTK_OBJECT (window_main), "window_main", window_main);
  gtk_window_set_title (GTK_WINDOW (window_main), "window");
  gtk_window_set_position (GTK_WINDOW (window_main), GTK_WIN_POS_CENTER);
  gtk_window_set_default_size (GTK_WINDOW (window_main), 400, 300);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox1);
  gtk_object_set_data_full (GTK_OBJECT (window_main), "vbox1", vbox1,
			    (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (window_main), vbox1);

  menubar1 = gtk_menu_bar_new ();
  gtk_widget_ref (menubar1);
  gtk_object_set_data_full (GTK_OBJECT (window_main), "menubar1", menubar1,
			    (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (menubar1);
  gtk_box_pack_start (GTK_BOX (vbox1), menubar1, FALSE, FALSE, 0);

  file1 = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (file1)->child),
				   "_File");
  gtk_widget_add_accelerator (file1, "activate_item", accel_group,
			      tmp_key, GDK_MOD1_MASK, 0);
  gtk_widget_ref (file1);
  gtk_object_set_data_full (GTK_OBJECT (window_main), "file1", file1,
			    (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (file1);
  gtk_container_add (GTK_CONTAINER (menubar1), file1);

  hpaned1 = gtk_hpaned_new ();
  gtk_widget_ref (hpaned1);
  gtk_object_set_data_full (GTK_OBJECT (window_main), "hpaned1", hpaned1,
			    (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hpaned1);
  gtk_box_pack_start (GTK_BOX (vbox1), hpaned1, TRUE, TRUE, 0);
  gtk_paned_set_position (GTK_PANED (hpaned1), 300);

  drawingarea1 = gtk_drawing_area_new ();
  gtk_widget_ref (drawingarea1);
  gtk_object_set_data_full (GTK_OBJECT (window_main), "drawingarea1", drawingarea1,
			    (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (drawingarea1);
  gtk_container_add (GTK_CONTAINER (hpaned1), drawingarea1);

  hscale1 = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, 0, 0, 0, 0, 0)));
  gtk_widget_ref (hscale1);
  gtk_object_set_data_full (GTK_OBJECT (window_main), "hscale1", hscale1,
			    (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hscale1);
  gtk_container_add (GTK_CONTAINER (hpaned1), hscale1);
  gtk_scale_set_draw_value (GTK_SCALE (hscale1), FALSE);

  statusbar1 = gtk_statusbar_new ();
  gtk_widget_ref (statusbar1);
  gtk_object_set_data_full (GTK_OBJECT (window_main), "statusbar1", statusbar1,
			    (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (statusbar1);
  gtk_box_pack_start (GTK_BOX (vbox1), statusbar1, FALSE, FALSE, 0);

  gtk_signal_connect (GTK_OBJECT (file1), "activate",
		      GTK_SIGNAL_FUNC (on_file1_activate),
		      NULL);
  gtk_signal_connect (GTK_OBJECT (drawingarea1), "configure_event",
		      GTK_SIGNAL_FUNC (on_drawingarea1_configure_event),
		      NULL);
  gtk_signal_connect (GTK_OBJECT (drawingarea1), "expose_event",
		      GTK_SIGNAL_FUNC (on_drawingarea1_expose_event),
		      NULL);

  gtk_window_add_accel_group (GTK_WINDOW (window_main), accel_group);

  return window_main;
}
