
/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget *create_app1 (void);
GtkWidget *create_about2 (void);
GtkWidget *create_node_popup (void);
GtkWidget *create_messagebox1 (void);
GtkWidget *create_diag_pref (void);
GtkWidget *create_fontselectiondialog1 (void);
GtkWidget *create_dialog2 (void);
