/* This file is automatically created by make tcp.h */

/* Etherape
* Copyright (C) 2000 Juan Toledo
* $Id$
*
* This program is free software; you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation; either version 2 of the License, or
* (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License
* along with this program; if not, write to the Free Software
* Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
*/
#define TCP_SERVICES     186
typedef enum
{
  TCP_TCPMUX = 1,		/* TCP PORT SERVICE MULTIPLEXER */
  TCP_ECHO = 7,
  TCP_DISCARD = 9,
  TCP_SYSTAT = 11,
  TCP_DAYTIME = 13,
  TCP_NETSTAT = 15,
  TCP_QOTD = 17,
  TCP_MSP = 18,			/* MESSAGE SEND PROTOCOL */
  TCP_CHARGEN = 19,
  TCP_FTP_DATA = 20,
  TCP_FTP = 21,
  TCP_SSH = 22,			/* SSH REMOTE LOGIN PROTOCOL */
  TCP_TELNET = 23,
  TCP_SMTP = 25,
  TCP_TIME = 37,
  TCP_NAMESERVER = 42,		/* IEN 116 */
  TCP_WHOIS = 43,
  TCP_RE_MAIL_CK = 50,		/* REMOTE MAIL CHECKING PROTOCOL */
  TCP_DOMAIN = 53,		/* NAME_DOMAIN SERVER */
  TCP_MTP = 57,			/* DEPRECATED */
  TCP_BOOTPS = 67,		/* BOOTP SERVER */
  TCP_BOOTPC = 68,		/* BOOTP CLIENT */
  TCP_GOPHER = 70,		/* INTERNET GOPHER */
  TCP_RJE = 77,
  TCP_FINGER = 79,
  TCP_WWW = 80,			/* WORLDWIDEWEB HTTP */
  TCP_LINK = 87,
  TCP_KERBEROS = 88,		/* KERBEROS V5 */
  TCP_SUPDUP = 95,
  TCP_HOSTNAMES = 101,		/* USUALLY FROM SRI_NIC */
  TCP_ISO_TSAP = 102,		/* PART OF ISODE. */
  TCP_CSNET_NS = 105,		/* ALSO USED BY CSO NAME SERVER */
  TCP_RTELNET = 107,		/* REMOTE TELNET */
  TCP_POP2 = 109,		/* POP VERSION 2 */
  TCP_POP3 = 110,		/* POP VERSION 3 */
  TCP_SUNRPC = 111,		/* RPC 4.0 PORTMAPPER TCP */
  TCP_AUTH = 113,
  TCP_SFTP = 115,
  TCP_UUCP_PATH = 117,
  TCP_NNTP = 119,		/* USENET NEWS TRANSFER PROTOCOL */
  TCP_NTP = 123,
  TCP_NETBIOS_NS = 137,		/* NETBIOS NAME SERVICE */
  TCP_NETBIOS_DGM = 138,	/* NETBIOS DATAGRAM SERVICE */
  TCP_NETBIOS_SSN = 139,	/* NETBIOS SESSION SERVICE */
  TCP_IMAP2 = 143,		/* INTERIM MAIL ACCESS PROTO V2 */
  TCP_CMIP_MAN = 163,		/* ISO MGMT OVER IP (CMOT) */
  TCP_CMIP_AGENT = 164,
  TCP_MAILQ = 174,		/* MAILER TRANSPORT QUEUE FOR ZMAILER */
  TCP_XDMCP = 177,		/* X DISPLAY MGR. CONTROL PROTO */
  TCP_NEXTSTEP = 178,		/* NEXTSTEP WINDOW */
  TCP_BGP = 179,		/* BORDER GATEWAY PROTO. */
  TCP_PROSPERO = 191,		/* CLIFF NEUMAN'S PROSPERO */
  TCP_IRC = 194,		/* INTERNET RELAY CHAT */
  TCP_SMUX = 199,		/* SNMP UNIX MULTIPLEXER */
  TCP_AT_RTMP = 201,		/* APPLETALK ROUTING */
  TCP_AT_NBP = 202,		/* APPLETALK NAME BINDING */
  TCP_AT_ECHO = 204,		/* APPLETALK ECHO */
  TCP_AT_ZIS = 206,		/* APPLETALK ZONE INFORMATION */
  TCP_QMTP = 209,		/* THE QUICK MAIL TRANSFER PROTOCOL */
  TCP_Z3950 = 210,		/* NISO Z39.50 DATABASE */
  TCP_IPX = 213,		/* IPX */
  TCP_IMAP3 = 220,		/* INTERACTIVE MAIL ACCESS */
  TCP_RPC2PORTMAP = 369,
  TCP_CODAAUTH2 = 370,
  TCP_ULISTSERV = 372,		/* UNIX LISTSERV */
  TCP_LDAP = 389,		/* LIGHTWEIGHT DIRECTORY ACCESS PROTOCOL */
  TCP_HTTPS = 443,		/* MCOM */
  TCP_SNPP = 444,		/* SIMPLE NETWORK PAGING PROTOCOL */
  TCP_SAFT = 487,		/* SIMPLE ASYNCHRONOUS FILE TRANSFER */
  TCP_NPMP_LOCAL = 610,		/* NPMP_LOCAL / DQS */
  TCP_NPMP_GUI = 611,		/* NPMP_GUI / DQS */
  TCP_HMMP_IND = 612,		/* HMMP INDICATION / DQS */
  TCP_IPP = 631,		/* INTERNET PRINTING PROTOCOL */
  TCP_EXEC = 512,
  TCP_LOGIN = 513,
  TCP_SHELL = 514,		/* NO PASSWORDS USED */
  TCP_PRINTER = 515,		/* LINE PRINTER SPOOLER */
  TCP_TEMPO = 526,
  TCP_COURIER = 530,
  TCP_CONFERENCE = 531,
  TCP_NETNEWS = 532,
  TCP_GDOMAP = 538,		/* GNUSTEP DISTRIBUTED OBJECTS */
  TCP_UUCP = 540,		/* UUCP DAEMON */
  TCP_AFPOVERTCP = 548,		/* AFP OVER TCP */
  TCP_REMOTEFS = 556,		/* BRUNHOFF REMOTE FILESYSTEM */
  TCP_KLOGIN = 543,		/* KERBERIZED `RLOGIN' (V5) */
  TCP_KSHELL = 544,		/* KERBERIZED `RSH' (V5) */
  TCP_NNTPS = 563,		/* NNTP OVER SSL */
  TCP_LDAPS = 636,		/* LDAP OVER SSL */
  TCP_KERBEROS_ADM = 749,	/* KERBEROS `KADMIN' (V5) */
  TCP_WEBSTER = 765,		/* NETWORK DICTIONARY */
  TCP_RSYNC = 873,		/* RSYNC */
  TCP_IMAPS = 993,		/* IMAP OVER SSL */
  TCP_IRCS = 994,		/* IRC OVER SSL */
  TCP_POP3S = 995,		/* POP_3 OVER SSL */
  TCP_SOCKS = 1080,		/* SOCKS PROXY SERVER */
  TCP_INGRESLOCK = 1524,
  TCP_PROSPERO_NP = 1525,	/* PROSPERO NON_PRIVILEGED */
  TCP_DATAMETRICS = 1645,	/* DATAMETRICS / OLD RADIUS ENTRY */
  TCP_SA_MSG_PORT = 1646,	/* SA_MSG_PORT / OLD RADACCT ENTRY */
  TCP_RADIUS = 1812,		/* RADIUS */
  TCP_RADACCT = 1813,		/* RADIUS ACCOUNTING */
  TCP_RTCM_SC104 = 2101,	/* RTCM SC_104 IANA 1/29/99 */
  TCP_CVSPSERVER = 2401,	/* CVS CLIENT/SERVER OPERATIONS */
  TCP_VENUS = 2430,		/* CODACON PORT */
  TCP_VENUS_SE = 2431,		/* TCP SIDE EFFECTS */
  TCP_CODASRV = 2432,		/* NOT USED */
  TCP_CODASRV_SE = 2433,	/* TCP SIDE EFFECTS */
  TCP_DICT = 2628,		/* DICTIONARY SERVER */
  TCP_ICPV2 = 3130,		/* INTERNET CACHE PROTOCOL (SQUID) */
  TCP_MYSQL = 3306,		/* MYSQL */
  TCP_RFE = 5002,		/* RADIO FREE ETHERNET */
  TCP_CFENGINE = 5308,		/* CFENGINE */
  TCP_XWINDOWS = 6000,
  TCP_AFS3_FILESERVER = 7000,	/* FILE SERVER ITSELF */
  TCP_AFS3_CALLBACK = 7001,	/* CALLBACKS TO CACHE MANAGERS */
  TCP_AFS3_PRSERVER = 7002,	/* USERS & GROUPS DATABASE */
  TCP_AFS3_VLSERVER = 7003,	/* VOLUME LOCATION DATABASE */
  TCP_AFS3_KASERVER = 7004,	/* AFS/KERBEROS AUTHENTICATION */
  TCP_AFS3_VOLSER = 7005,	/* VOLUME MANAGMENT SERVER */
  TCP_AFS3_ERRORS = 7006,	/* ERROR INTERPRETATION SERVICE */
  TCP_AFS3_BOS = 7007,		/* BASIC OVERSEER PROCESS */
  TCP_AFS3_UPDATE = 7008,	/* SERVER_TO_SERVER UPDATER */
  TCP_AFS3_RMTSYS = 7009,	/* REMOTE CACHE MANAGER SERVICE */
  TCP_FONT_SERVICE = 7100,	/* X FONT SERVICE */
  TCP_WNN6 = 22273,		/* WNN6 */
  TCP_KERBEROS4 = 750,		/* KERBEROS (SERVER) TCP */
  TCP_KERBEROS_MASTER = 751,	/* KERBEROS AUTHENTICATION */
  TCP_KRB_PROP = 754,		/* KERBEROS SLAVE PROPAGATION */
  TCP_KRBUPDATE = 760,		/* KERBEROS REGISTRATION */
  TCP_KPASSWD = 761,		/* KERBEROS "PASSWD" */
  TCP_KPOP = 1109,		/* POP WITH KERBEROS */
  TCP_KNETD = 2053,		/* KERBEROS DE_MULTIPLEXOR */
  TCP_EKLOGIN = 2105,		/* KERBEROS ENCRYPTED RLOGIN */
  TCP_KX = 2111,		/* X OVER KERBEROS */
  TCP_SUPFILESRV = 871,		/* SUP SERVER */
  TCP_SUPFILEDBG = 1127,	/* SUP DEBUGGING */
  TCP_LINUXCONF = 98,		/* LINUXCONF */
  TCP_POPPASSD = 106,		/* EUDORA */
  TCP_SSMTP = 465,		/* SMTP OVER SSL */
  TCP_NQS = 607,		/* NETWORK QUEUING SYSTEM */
  TCP_MOIRA_DB = 775,		/* MOIRA DATABASE */
  TCP_MOIRA_UPDATE = 777,	/* MOIRA UPDATE PROTOCOL. */
  TCP_OMIRR = 808,		/* ONLINE MIRROR */
  TCP_SWAT = 901,		/* SAMBA CONFIGURATION TOOL */
  TCP_CUSTOMS = 1001,		/* PMAKE CUSTOMS SERVER */
  TCP_RMIREGISTRY = 1099,	/* JAVA RMI REGISTRY */
  TCP_SKKSERV = 1178,		/* SKK JISHO SERVER PORT */
  TCP_RMTCFG = 1236,		/* GRACILIS PACKETEN REMOTE CONFIG SERVER */
  TCP_XTEL = 1313,		/* FRENCH MINITEL */
  TCP_SUPPORT = 1529,		/* GNATS */
  TCP_CFINGER = 2003,		/* GNU FINGER */
  TCP_NDTP = 2010,		/* NETWORK DICTIONARY TRANSFER PROTOCOL */
  TCP_NINSTALL = 2150,		/* NINSTALL SERVICE */
  TCP_ZEBRASRV = 2600,		/* ZEBRA SERVICE */
  TCP_ZEBRA = 2601,		/* ZEBRA VTY */
  TCP_RIPD = 2602,		/* RIPD VTY */
  TCP_RIPNGD = 2603,		/* RIPNGD VTY */
  TCP_OSPFD = 2604,		/* OSPFD VTY */
  TCP_BGPD = 2605,		/* BGPD VTY */
  TCP_OSPF6D = 2606,		/* OSPF6D VTY */
  TCP_AFBACKUP = 2988,		/* AFBACKUP SYSTEM */
  TCP_AFMBACKUP = 2989,		/* AFMBACKUP SYSTEM */
  TCP_FAX = 4557,		/* FAX TRANSMISSION SERVICE        (OLD) */
  TCP_HYLAFAX = 4559,		/* HYLAFAX CLIENT_SERVER PROTOCOL  (NEW) */
  TCP_NOCLOG = 5354,		/* NOCLOGD WITH TCP (NOCOL) */
  TCP_HOSTMON = 5355,		/* HOSTMON USES TCP (NOCOL) */
  TCP_POSTGRES = 5432,		/* POSTGRES */
  TCP_MRTD = 5674,		/* MRT ROUTING DAEMON */
  TCP_BGPSIM = 5675,		/* MRT ROUTING SIMULATOR */
  TCP_CANNA = 5680,		/* CANNASERVER */
  TCP_SANE = 6566,		/* SANE NETWORK SCANNER DAEMON */
  TCP_IRCD = 6667,		/* INTERNET RELAY CHAT */
  TCP_IRCD_DALNET = 7000,	/* IRC _ DALNET */
  TCP_WEBCACHE = 8080,		/* WWW CACHING SERVICE */
  TCP_TPROXY = 8081,		/* TRANSPARENT PROXY */
  TCP_OMNIORB = 8088,		/* OMNIORB */
  TCP_KAMANDA = 10081,		/* AMANDA BACKUP SERVICES (KERBEROS) */
  TCP_AMANDAIDX = 10082,	/* AMANDA BACKUP SERVICES */
  TCP_AMIDXTAPE = 10083,	/* AMANDA BACKUP SERVICES */
  TCP_ISDNLOG = 20011,		/* ISDN LOGGING SYSTEM */
  TCP_VBOXD = 20012,		/* VOICE BOX SYSTEM */
  TCP_BINKP = 24554,		/* BINKLEY */
  TCP_ASP = 27374,		/* ADDRESS SEARCH PROTOCOL */
  TCP_TFIDO = 60177,		/* IFMAIL */
  TCP_FIDO = 60179,		/* IFMAIL */
  TCP_DUMMY = 99999
}
tcp_type_t;
#define UDP_SERVICES     134
typedef enum
{
  UDP_ECHO = 7,
  UDP_DISCARD = 9,
  UDP_DAYTIME = 13,
  UDP_MSP = 18,			/* MESSAGE SEND PROTOCOL */
  UDP_CHARGEN = 19,
  UDP_FSP = 21,
  UDP_SSH = 22,			/* SSH REMOTE LOGIN PROTOCOL */
  UDP_TIME = 37,
  UDP_RLP = 39,			/* RESOURCE LOCATION */
  UDP_RE_MAIL_CK = 50,		/* REMOTE MAIL CHECKING PROTOCOL */
  UDP_DOMAIN = 53,
  UDP_BOOTPS = 67,
  UDP_BOOTPC = 68,
  UDP_TFTP = 69,
  UDP_GOPHER = 70,
  UDP_WWW = 80,			/* HYPERTEXT TRANSFER PROTOCOL */
  UDP_KERBEROS = 88,		/* KERBEROS V5 */
  UDP_CSNET_NS = 105,
  UDP_RTELNET = 107,
  UDP_POP2 = 109,
  UDP_POP3 = 110,
  UDP_SUNRPC = 111,		/* RPC 4.0 PORTMAPPER UDP */
  UDP_NTP = 123,		/* NETWORK TIME PROTOCOL */
  UDP_NETBIOS_NS = 137,
  UDP_NETBIOS_DGM = 138,
  UDP_NETBIOS_SSN = 139,
  UDP_IMAP2 = 143,
  UDP_SNMP = 161,		/* SIMPLE NET MGMT PROTO */
  UDP_SNMP_TRAP = 162,		/* TRAPS FOR SNMP */
  UDP_CMIP_MAN = 163,
  UDP_CMIP_AGENT = 164,
  UDP_MAILQ = 174,		/* MAILER TRANSPORT QUEUE FOR ZMAILER */
  UDP_XDMCP = 177,
  UDP_NEXTSTEP = 178,		/* SERVER */
  UDP_BGP = 179,
  UDP_PROSPERO = 191,
  UDP_IRC = 194,
  UDP_SMUX = 199,
  UDP_AT_RTMP = 201,
  UDP_AT_NBP = 202,
  UDP_AT_ECHO = 204,
  UDP_AT_ZIS = 206,
  UDP_QMTP = 209,		/* THE QUICK MAIL TRANSFER PROTOCOL */
  UDP_Z3950 = 210,
  UDP_IPX = 213,
  UDP_IMAP3 = 220,		/* PROTOCOL V3 */
  UDP_RPC2PORTMAP = 369,	/* CODA PORTMAPPER */
  UDP_CODAAUTH2 = 370,		/* CODA AUTHENTICATION SERVER */
  UDP_ULISTSERV = 372,
  UDP_LDAP = 389,		/* LIGHTWEIGHT DIRECTORY ACCESS PROTOCOL */
  UDP_HTTPS = 443,		/* MCOM */
  UDP_SNPP = 444,		/* SIMPLE NETWORK PAGING PROTOCOL */
  UDP_SAFT = 487,		/* SIMPLE ASYNCHRONOUS FILE TRANSFER */
  UDP_NPMP_LOCAL = 610,		/* NPMP_LOCAL / DQS */
  UDP_NPMP_GUI = 611,		/* NPMP_GUI / DQS */
  UDP_HMMP_IND = 612,		/* HMMP INDICATION / DQS */
  UDP_IPP = 631,		/* INTERNET PRINTING PROTOCOL */
  UDP_BIFF = 512,
  UDP_WHO = 513,
  UDP_SYSLOG = 514,
  UDP_TALK = 517,
  UDP_NTALK = 518,
  UDP_ROUTE = 520,		/* RIP */
  UDP_TIMED = 525,
  UDP_NETWALL = 533,		/* _FOR EMERGENCY BROADCASTS */
  UDP_GDOMAP = 538,		/* GNUSTEP DISTRIBUTED OBJECTS */
  UDP_AFPOVERTCP = 548,		/* AFP OVER TCP */
  UDP_NNTPS = 563,		/* NNTP OVER SSL */
  UDP_LDAPS = 636,		/* LDAP OVER SSL */
  UDP_WEBSTER = 765,
  UDP_RSYNC = 873,		/* RSYNC */
  UDP_IMAPS = 993,		/* IMAP OVER SSL */
  UDP_IRCS = 994,		/* IRC OVER SSL */
  UDP_POP3S = 995,		/* POP_3 OVER SSL */
  UDP_SOCKS = 1080,		/* SOCKS PROXY SERVER */
  UDP_INGRESLOCK = 1524,
  UDP_PROSPERO_NP = 1525,
  UDP_DATAMETRICS = 1645,	/* DATAMETRICS / OLD RADIUS ENTRY */
  UDP_SA_MSG_PORT = 1646,	/* SA_MSG_PORT / OLD RADACCT ENTRY */
  UDP_RADIUS = 1812,		/* RADIUS */
  UDP_RADACCT = 1813,		/* RADIUS ACCOUNTING */
  UDP_RTCM_SC104 = 2101,	/* RTCM SC_104 IANA 1/29/99 */
  UDP_CVSPSERVER = 2401,	/* CVS CLIENT/SERVER OPERATIONS */
  UDP_VENUS = 2430,		/* VENUS CALLBACK/WBC INTERFACE */
  UDP_VENUS_SE = 2431,		/* UDP SFTP SIDE EFFECT */
  UDP_CODASRV = 2432,		/* SERVER PORT */
  UDP_CODASRV_SE = 2433,	/* UDP SFTP SIDE EFFECT */
  UDP_DICT = 2628,		/* DICTIONARY SERVER */
  UDP_ICPV2 = 3130,		/* INTERNET CACHE PROTOCOL (SQUID) */
  UDP_MYSQL = 3306,		/* MYSQL */
  UDP_RFE = 5002,		/* ACTUALLY USES UDP ONLY */
  UDP_CFENGINE = 5308,		/* CFENGINE */
  UDP_AFS3_FILESERVER = 7000,	/* FILE SERVER ITSELF */
  UDP_AFS3_CALLBACK = 7001,	/* CALLBACKS TO CACHE MANAGERS */
  UDP_AFS3_PRSERVER = 7002,	/* USERS & GROUPS DATABASE */
  UDP_AFS3_VLSERVER = 7003,	/* VOLUME LOCATION DATABASE */
  UDP_AFS3_KASERVER = 7004,	/* AFS/KERBEROS AUTHENTICATION */
  UDP_AFS3_VOLSER = 7005,	/* VOLUME MANAGMENT SERVER */
  UDP_AFS3_ERRORS = 7006,	/* ERROR INTERPRETATION SERVICE */
  UDP_AFS3_BOS = 7007,		/* BASIC OVERSEER PROCESS */
  UDP_AFS3_UPDATE = 7008,	/* SERVER_TO_SERVER UPDATER */
  UDP_AFS3_RMTSYS = 7009,	/* REMOTE CACHE MANAGER SERVICE */
  UDP_FONT_SERVICE = 7100,	/* X FONT SERVICE */
  UDP_WNN6 = 22273,		/* WNN6 */
  UDP_KERBEROS4 = 750,		/* KERBEROS (SERVER) UDP */
  UDP_KERBEROS_MASTER = 751,	/* KERBEROS AUTHENTICATION */
  UDP_PASSWD_SERVER = 752,	/* KERBEROS PASSWD SERVER */
  UDP_ZEPHYR_SRV = 2102,	/* ZEPHYR SERVER */
  UDP_ZEPHYR_CLT = 2103,	/* ZEPHYR SERV_HM CONNECTION */
  UDP_ZEPHYR_HM = 2104,		/* ZEPHYR HOSTMANAGER */
  UDP_POPPASSD = 106,		/* EUDORA */
  UDP_MOIRA_UREG = 779,		/* MOIRA USER REGISTRATION. */
  UDP_OMIRR = 808,		/* ONLINE MIRROR */
  UDP_CUSTOMS = 1001,		/* PMAKE CUSTOMS SERVER */
  UDP_NINSTALL = 2150,		/* NINSTALL SERVICE */
  UDP_AFBACKUP = 2988,		/* AFBACKUP SYSTEM */
  UDP_AFMBACKUP = 2989,		/* AFMBACKUP SYSTEM */
  UDP_NOCLOG = 5354,		/* NOCLOGD WITH UDP (NOCOL) */
  UDP_HOSTMON = 5355,		/* HOSTMON USES TCP (NOCOL) */
  UDP_POSTGRES = 5432,		/* POSTGRES */
  UDP_IRCD = 6667,		/* INTERNET RELAY CHAT */
  UDP_IRCD_DALNET = 7000,	/* IRC _ DALNET */
  UDP_WEBCACHE = 8080,		/* WWW CACHING SERVICE */
  UDP_TPROXY = 8081,		/* TRANSPARENT PROXY */
  UDP_OMNIORB = 8088,		/* OMNIORB */
  UDP_MANDELSPAWN = 9359,	/* NETWORK MANDELBROT */
  UDP_AMANDA = 10080,		/* AMANDA BACKUP SERVICES */
  UDP_KAMANDA = 10081,		/* AMANDA BACKUP SERVICES (KERBEROS) */
  UDP_ISDNLOG = 20011,		/* ISDN LOGGING SYSTEM */
  UDP_VBOXD = 20012,		/* VOICE BOX SYSTEM */
  UDP_BINKP = 24554,		/* BINKLEY */
  UDP_ASP = 27374,		/* ADDRESS SEARCH PROTOCOL */
  UDP_TFIDO = 60177,		/* IFMAIL */
  UDP_FIDO = 60179,		/* IFMAIL */
  UDP_DUMMY = 99999
}
udp_type_t;

typedef struct
{
  tcp_type_t number;
  gchar *name;
}
tcp_service_t;

static tcp_service_t tcp_services_table[TCP_SERVICES + 1] = {
  {TCP_TCPMUX, "TCPMUX"},
  {TCP_ECHO, "ECHO"},
  {TCP_DISCARD, "DISCARD"},
  {TCP_SYSTAT, "SYSTAT"},
  {TCP_DAYTIME, "DAYTIME"},
  {TCP_NETSTAT, "NETSTAT"},
  {TCP_QOTD, "QOTD"},
  {TCP_MSP, "MSP"},
  {TCP_CHARGEN, "CHARGEN"},
  {TCP_FTP_DATA, "FTP_DATA"},
  {TCP_FTP, "FTP"},
  {TCP_SSH, "SSH"},
  {TCP_TELNET, "TELNET"},
  {TCP_SMTP, "SMTP"},
  {TCP_TIME, "TIME"},
  {TCP_NAMESERVER, "NAMESERVER"},
  {TCP_WHOIS, "WHOIS"},
  {TCP_RE_MAIL_CK, "RE_MAIL_CK"},
  {TCP_DOMAIN, "DOMAIN"},
  {TCP_MTP, "MTP"},
  {TCP_BOOTPS, "BOOTPS"},
  {TCP_BOOTPC, "BOOTPC"},
  {TCP_GOPHER, "GOPHER"},
  {TCP_RJE, "RJE"},
  {TCP_FINGER, "FINGER"},
  {TCP_WWW, "WWW"},
  {TCP_LINK, "LINK"},
  {TCP_KERBEROS, "KERBEROS"},
  {TCP_SUPDUP, "SUPDUP"},
  {TCP_HOSTNAMES, "HOSTNAMES"},
  {TCP_ISO_TSAP, "ISO_TSAP"},
  {TCP_CSNET_NS, "CSNET_NS"},
  {TCP_RTELNET, "RTELNET"},
  {TCP_POP2, "POP2"},
  {TCP_POP3, "POP3"},
  {TCP_SUNRPC, "SUNRPC"},
  {TCP_AUTH, "AUTH"},
  {TCP_SFTP, "SFTP"},
  {TCP_UUCP_PATH, "UUCP_PATH"},
  {TCP_NNTP, "NNTP"},
  {TCP_NTP, "NTP"},
  {TCP_NETBIOS_NS, "NETBIOS_NS"},
  {TCP_NETBIOS_DGM, "NETBIOS_DGM"},
  {TCP_NETBIOS_SSN, "NETBIOS_SSN"},
  {TCP_IMAP2, "IMAP2"},
  {TCP_CMIP_MAN, "CMIP_MAN"},
  {TCP_CMIP_AGENT, "CMIP_AGENT"},
  {TCP_MAILQ, "MAILQ"},
  {TCP_XDMCP, "XDMCP"},
  {TCP_NEXTSTEP, "NEXTSTEP"},
  {TCP_BGP, "BGP"},
  {TCP_PROSPERO, "PROSPERO"},
  {TCP_IRC, "IRC"},
  {TCP_SMUX, "SMUX"},
  {TCP_AT_RTMP, "AT_RTMP"},
  {TCP_AT_NBP, "AT_NBP"},
  {TCP_AT_ECHO, "AT_ECHO"},
  {TCP_AT_ZIS, "AT_ZIS"},
  {TCP_QMTP, "QMTP"},
  {TCP_Z3950, "Z3950"},
  {TCP_IPX, "IPX"},
  {TCP_IMAP3, "IMAP3"},
  {TCP_RPC2PORTMAP, "RPC2PORTMAP"},
  {TCP_CODAAUTH2, "CODAAUTH2"},
  {TCP_ULISTSERV, "ULISTSERV"},
  {TCP_LDAP, "LDAP"},
  {TCP_HTTPS, "HTTPS"},
  {TCP_SNPP, "SNPP"},
  {TCP_SAFT, "SAFT"},
  {TCP_NPMP_LOCAL, "NPMP_LOCAL"},
  {TCP_NPMP_GUI, "NPMP_GUI"},
  {TCP_HMMP_IND, "HMMP_IND"},
  {TCP_IPP, "IPP"},
  {TCP_EXEC, "EXEC"},
  {TCP_LOGIN, "LOGIN"},
  {TCP_SHELL, "SHELL"},
  {TCP_PRINTER, "PRINTER"},
  {TCP_TEMPO, "TEMPO"},
  {TCP_COURIER, "COURIER"},
  {TCP_CONFERENCE, "CONFERENCE"},
  {TCP_NETNEWS, "NETNEWS"},
  {TCP_GDOMAP, "GDOMAP"},
  {TCP_UUCP, "UUCP"},
  {TCP_AFPOVERTCP, "AFPOVERTCP"},
  {TCP_REMOTEFS, "REMOTEFS"},
  {TCP_KLOGIN, "KLOGIN"},
  {TCP_KSHELL, "KSHELL"},
  {TCP_NNTPS, "NNTPS"},
  {TCP_LDAPS, "LDAPS"},
  {TCP_KERBEROS_ADM, "KERBEROS_ADM"},
  {TCP_WEBSTER, "WEBSTER"},
  {TCP_RSYNC, "RSYNC"},
  {TCP_IMAPS, "IMAPS"},
  {TCP_IRCS, "IRCS"},
  {TCP_POP3S, "POP3S"},
  {TCP_SOCKS, "SOCKS"},
  {TCP_INGRESLOCK, "INGRESLOCK"},
  {TCP_PROSPERO_NP, "PROSPERO_NP"},
  {TCP_DATAMETRICS, "DATAMETRICS"},
  {TCP_SA_MSG_PORT, "SA_MSG_PORT"},
  {TCP_RADIUS, "RADIUS"},
  {TCP_RADACCT, "RADACCT"},
  {TCP_RTCM_SC104, "RTCM_SC104"},
  {TCP_CVSPSERVER, "CVSPSERVER"},
  {TCP_VENUS, "VENUS"},
  {TCP_VENUS_SE, "VENUS_SE"},
  {TCP_CODASRV, "CODASRV"},
  {TCP_CODASRV_SE, "CODASRV_SE"},
  {TCP_DICT, "DICT"},
  {TCP_ICPV2, "ICPV2"},
  {TCP_MYSQL, "MYSQL"},
  {TCP_RFE, "RFE"},
  {TCP_CFENGINE, "CFENGINE"},
  {TCP_XWINDOWS, "XWINDOWS"},
  {TCP_AFS3_FILESERVER, "AFS3_FILESERVER"},
  {TCP_AFS3_CALLBACK, "AFS3_CALLBACK"},
  {TCP_AFS3_PRSERVER, "AFS3_PRSERVER"},
  {TCP_AFS3_VLSERVER, "AFS3_VLSERVER"},
  {TCP_AFS3_KASERVER, "AFS3_KASERVER"},
  {TCP_AFS3_VOLSER, "AFS3_VOLSER"},
  {TCP_AFS3_ERRORS, "AFS3_ERRORS"},
  {TCP_AFS3_BOS, "AFS3_BOS"},
  {TCP_AFS3_UPDATE, "AFS3_UPDATE"},
  {TCP_AFS3_RMTSYS, "AFS3_RMTSYS"},
  {TCP_FONT_SERVICE, "FONT_SERVICE"},
  {TCP_WNN6, "WNN6"},
  {TCP_KERBEROS4, "KERBEROS4"},
  {TCP_KERBEROS_MASTER, "KERBEROS_MASTER"},
  {TCP_KRB_PROP, "KRB_PROP"},
  {TCP_KRBUPDATE, "KRBUPDATE"},
  {TCP_KPASSWD, "KPASSWD"},
  {TCP_KPOP, "KPOP"},
  {TCP_KNETD, "KNETD"},
  {TCP_EKLOGIN, "EKLOGIN"},
  {TCP_KX, "KX"},
  {TCP_SUPFILESRV, "SUPFILESRV"},
  {TCP_SUPFILEDBG, "SUPFILEDBG"},
  {TCP_LINUXCONF, "LINUXCONF"},
  {TCP_POPPASSD, "POPPASSD"},
  {TCP_SSMTP, "SSMTP"},
  {TCP_NQS, "NQS"},
  {TCP_MOIRA_DB, "MOIRA_DB"},
  {TCP_MOIRA_UPDATE, "MOIRA_UPDATE"},
  {TCP_OMIRR, "OMIRR"},
  {TCP_SWAT, "SWAT"},
  {TCP_CUSTOMS, "CUSTOMS"},
  {TCP_RMIREGISTRY, "RMIREGISTRY"},
  {TCP_SKKSERV, "SKKSERV"},
  {TCP_RMTCFG, "RMTCFG"},
  {TCP_XTEL, "XTEL"},
  {TCP_SUPPORT, "SUPPORT"},
  {TCP_CFINGER, "CFINGER"},
  {TCP_NDTP, "NDTP"},
  {TCP_NINSTALL, "NINSTALL"},
  {TCP_ZEBRASRV, "ZEBRASRV"},
  {TCP_ZEBRA, "ZEBRA"},
  {TCP_RIPD, "RIPD"},
  {TCP_RIPNGD, "RIPNGD"},
  {TCP_OSPFD, "OSPFD"},
  {TCP_BGPD, "BGPD"},
  {TCP_OSPF6D, "OSPF6D"},
  {TCP_AFBACKUP, "AFBACKUP"},
  {TCP_AFMBACKUP, "AFMBACKUP"},
  {TCP_FAX, "FAX"},
  {TCP_HYLAFAX, "HYLAFAX"},
  {TCP_NOCLOG, "NOCLOG"},
  {TCP_HOSTMON, "HOSTMON"},
  {TCP_POSTGRES, "POSTGRES"},
  {TCP_MRTD, "MRTD"},
  {TCP_BGPSIM, "BGPSIM"},
  {TCP_CANNA, "CANNA"},
  {TCP_SANE, "SANE"},
  {TCP_IRCD, "IRCD"},
  {TCP_IRCD_DALNET, "IRCD_DALNET"},
  {TCP_WEBCACHE, "WEBCACHE"},
  {TCP_TPROXY, "TPROXY"},
  {TCP_OMNIORB, "OMNIORB"},
  {TCP_KAMANDA, "KAMANDA"},
  {TCP_AMANDAIDX, "AMANDAIDX"},
  {TCP_AMIDXTAPE, "AMIDXTAPE"},
  {TCP_ISDNLOG, "ISDNLOG"},
  {TCP_VBOXD, "VBOXD"},
  {TCP_BINKP, "BINKP"},
  {TCP_ASP, "ASP"},
  {TCP_TFIDO, "TFIDO"},
  {TCP_FIDO, "FIDO"},
  {TCP_DUMMY, "DUMMY"}
};

typedef struct
{
  udp_type_t number;
  gchar *name;
}
udp_service_t;

static udp_service_t udp_services_table[UDP_SERVICES + 1] = {
  {UDP_ECHO, "ECHO"},
  {UDP_DISCARD, "DISCARD"},
  {UDP_DAYTIME, "DAYTIME"},
  {UDP_MSP, "MSP"},
  {UDP_CHARGEN, "CHARGEN"},
  {UDP_FSP, "FSP"},
  {UDP_SSH, "SSH"},
  {UDP_TIME, "TIME"},
  {UDP_RLP, "RLP"},
  {UDP_RE_MAIL_CK, "RE_MAIL_CK"},
  {UDP_DOMAIN, "DOMAIN"},
  {UDP_BOOTPS, "BOOTPS"},
  {UDP_BOOTPC, "BOOTPC"},
  {UDP_TFTP, "TFTP"},
  {UDP_GOPHER, "GOPHER"},
  {UDP_WWW, "WWW"},
  {UDP_KERBEROS, "KERBEROS"},
  {UDP_CSNET_NS, "CSNET_NS"},
  {UDP_RTELNET, "RTELNET"},
  {UDP_POP2, "POP2"},
  {UDP_POP3, "POP3"},
  {UDP_SUNRPC, "SUNRPC"},
  {UDP_NTP, "NTP"},
  {UDP_NETBIOS_NS, "NETBIOS_NS"},
  {UDP_NETBIOS_DGM, "NETBIOS_DGM"},
  {UDP_NETBIOS_SSN, "NETBIOS_SSN"},
  {UDP_IMAP2, "IMAP2"},
  {UDP_SNMP, "SNMP"},
  {UDP_SNMP_TRAP, "SNMP_TRAP"},
  {UDP_CMIP_MAN, "CMIP_MAN"},
  {UDP_CMIP_AGENT, "CMIP_AGENT"},
  {UDP_MAILQ, "MAILQ"},
  {UDP_XDMCP, "XDMCP"},
  {UDP_NEXTSTEP, "NEXTSTEP"},
  {UDP_BGP, "BGP"},
  {UDP_PROSPERO, "PROSPERO"},
  {UDP_IRC, "IRC"},
  {UDP_SMUX, "SMUX"},
  {UDP_AT_RTMP, "AT_RTMP"},
  {UDP_AT_NBP, "AT_NBP"},
  {UDP_AT_ECHO, "AT_ECHO"},
  {UDP_AT_ZIS, "AT_ZIS"},
  {UDP_QMTP, "QMTP"},
  {UDP_Z3950, "Z3950"},
  {UDP_IPX, "IPX"},
  {UDP_IMAP3, "IMAP3"},
  {UDP_RPC2PORTMAP, "RPC2PORTMAP"},
  {UDP_CODAAUTH2, "CODAAUTH2"},
  {UDP_ULISTSERV, "ULISTSERV"},
  {UDP_LDAP, "LDAP"},
  {UDP_HTTPS, "HTTPS"},
  {UDP_SNPP, "SNPP"},
  {UDP_SAFT, "SAFT"},
  {UDP_NPMP_LOCAL, "NPMP_LOCAL"},
  {UDP_NPMP_GUI, "NPMP_GUI"},
  {UDP_HMMP_IND, "HMMP_IND"},
  {UDP_IPP, "IPP"},
  {UDP_BIFF, "BIFF"},
  {UDP_WHO, "WHO"},
  {UDP_SYSLOG, "SYSLOG"},
  {UDP_TALK, "TALK"},
  {UDP_NTALK, "NTALK"},
  {UDP_ROUTE, "ROUTE"},
  {UDP_TIMED, "TIMED"},
  {UDP_NETWALL, "NETWALL"},
  {UDP_GDOMAP, "GDOMAP"},
  {UDP_AFPOVERTCP, "AFPOVERTCP"},
  {UDP_NNTPS, "NNTPS"},
  {UDP_LDAPS, "LDAPS"},
  {UDP_WEBSTER, "WEBSTER"},
  {UDP_RSYNC, "RSYNC"},
  {UDP_IMAPS, "IMAPS"},
  {UDP_IRCS, "IRCS"},
  {UDP_POP3S, "POP3S"},
  {UDP_SOCKS, "SOCKS"},
  {UDP_INGRESLOCK, "INGRESLOCK"},
  {UDP_PROSPERO_NP, "PROSPERO_NP"},
  {UDP_DATAMETRICS, "DATAMETRICS"},
  {UDP_SA_MSG_PORT, "SA_MSG_PORT"},
  {UDP_RADIUS, "RADIUS"},
  {UDP_RADACCT, "RADACCT"},
  {UDP_RTCM_SC104, "RTCM_SC104"},
  {UDP_CVSPSERVER, "CVSPSERVER"},
  {UDP_VENUS, "VENUS"},
  {UDP_VENUS_SE, "VENUS_SE"},
  {UDP_CODASRV, "CODASRV"},
  {UDP_CODASRV_SE, "CODASRV_SE"},
  {UDP_DICT, "DICT"},
  {UDP_ICPV2, "ICPV2"},
  {UDP_MYSQL, "MYSQL"},
  {UDP_RFE, "RFE"},
  {UDP_CFENGINE, "CFENGINE"},
  {UDP_AFS3_FILESERVER, "AFS3_FILESERVER"},
  {UDP_AFS3_CALLBACK, "AFS3_CALLBACK"},
  {UDP_AFS3_PRSERVER, "AFS3_PRSERVER"},
  {UDP_AFS3_VLSERVER, "AFS3_VLSERVER"},
  {UDP_AFS3_KASERVER, "AFS3_KASERVER"},
  {UDP_AFS3_VOLSER, "AFS3_VOLSER"},
  {UDP_AFS3_ERRORS, "AFS3_ERRORS"},
  {UDP_AFS3_BOS, "AFS3_BOS"},
  {UDP_AFS3_UPDATE, "AFS3_UPDATE"},
  {UDP_AFS3_RMTSYS, "AFS3_RMTSYS"},
  {UDP_FONT_SERVICE, "FONT_SERVICE"},
  {UDP_WNN6, "WNN6"},
  {UDP_KERBEROS4, "KERBEROS4"},
  {UDP_KERBEROS_MASTER, "KERBEROS_MASTER"},
  {UDP_PASSWD_SERVER, "PASSWD_SERVER"},
  {UDP_ZEPHYR_SRV, "ZEPHYR_SRV"},
  {UDP_ZEPHYR_CLT, "ZEPHYR_CLT"},
  {UDP_ZEPHYR_HM, "ZEPHYR_HM"},
  {UDP_POPPASSD, "POPPASSD"},
  {UDP_MOIRA_UREG, "MOIRA_UREG"},
  {UDP_OMIRR, "OMIRR"},
  {UDP_CUSTOMS, "CUSTOMS"},
  {UDP_NINSTALL, "NINSTALL"},
  {UDP_AFBACKUP, "AFBACKUP"},
  {UDP_AFMBACKUP, "AFMBACKUP"},
  {UDP_NOCLOG, "NOCLOG"},
  {UDP_HOSTMON, "HOSTMON"},
  {UDP_POSTGRES, "POSTGRES"},
  {UDP_IRCD, "IRCD"},
  {UDP_IRCD_DALNET, "IRCD_DALNET"},
  {UDP_WEBCACHE, "WEBCACHE"},
  {UDP_TPROXY, "TPROXY"},
  {UDP_OMNIORB, "OMNIORB"},
  {UDP_MANDELSPAWN, "MANDELSPAWN"},
  {UDP_AMANDA, "AMANDA"},
  {UDP_KAMANDA, "KAMANDA"},
  {UDP_ISDNLOG, "ISDNLOG"},
  {UDP_VBOXD, "VBOXD"},
  {UDP_BINKP, "BINKP"},
  {UDP_ASP, "ASP"},
  {UDP_TFIDO, "TFIDO"},
  {UDP_FIDO, "FIDO"},
  {UDP_DUMMY, "DUMMY"}
};
